"""empty message

Revision ID: 43523b717627
Revises: 148ad2443a4f
Create Date: 2022-05-14 05:58:06.732343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43523b717627'
down_revision = '148ad2443a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
